theme="poimandres"
# theme="catppuccin_mocha"
# theme="tokyonight"

[editor]
# mouse=false
line-number="relative"
gutters=["diff","diagnostics"]

[editor.file-picker]
hidden=false


[editor.whitespace.render]
space="all"
tab="none"
nbsp="none"
nnbsp="none"
newline="all"


[editor.indent-guides]
render=true
charachter="|"
skip-levels=1

[editor.cursor-shape]
insert="bar"
normal="block"
select="underline"
